name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ AKIA5OEL3CVEOI4YYGOA }}
        aws-secret-access-key: ${{ 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 }}
        aws-region: ap-south-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://static-website-on-aws-s3-with-github-actions
